### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by visnup** [observablehq/database-proxy#1]
Need to get correct now
- [ ] Encode port in secret, listen on union of ports, map port+name to db (support ports other than 2899)

Can do now to reduce future pain
- [ ] /check routes
- [ ] SSL trust
- [ ] Version assertion or way to inform backwards compatibility

Can do later
- [ ] Code re-use with hosted connectors
- [ ] BigQuery support (need to copy in credentials JSON file?)
